---
settings:
  name: Astra Family
  search: astra-control-service,astra-control-center,astra-automation,trident
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de la familia de productos Astra
    url: "/index.html"
